#!/bin/bash

#
# Starts Nodes per the platform  conf
##
sourceconf "$PLATFORM_CONF"


function _start_nodes(){

    echo "Setting the Default region"
    set_region ${INIT_REGION}

    echo "Setting up the masters"
    start_nodes "master"
    echo ""
    echo "Setting up the workers"
    start_nodes "worker"

}
_start_nodes "$@"



