#!/bin/bash

#
# Terminates nodes per the platform conf
##

sourceconf "$PLATFORM_CONF"

function _term_nodes(){
    for i in "$@"
    do
    case $i in
        -u)
        UNATTEND="1"
        ;;
        *)
    esac
    done



    INSTS="worker master"
    for INST in $INSTS; do
        echo "Terminating ${INST}s"
        term_nodes $INST $UNATTEND
    done
}
_term_nodes "$@"



