#!/bin/bash

#
# Terminates nodes per the platform conf
##

sourceconf "$PLATFORM_CONF"

function _term_nodes(){

    if [ ! -f "./bin/init_output.json" ]; then
        echo "No init_output.json found - No doing anything"
    else
        ret_init_inst "SPOT_INSTS"
        ret_init_ips "INST_STR" "$SPOT_INSTS" 1
        echo "$INST_STR"
        INST_STR=$(echo "$INST_STR"|tr ";" " ")
        echo "The init spot instances are: $SPOT_INSTS"
        echo ""
        echo "The current status is:"
        echo ""
        for I in $INST_STR; do
            echo "$I"
        done
        echo ""
        read -e -p "Are you SURE you wish to terminate these instances? (Y/N): " -i "N" TERM_CONFIRM

        if [ "$TERM_CONFIRM" == "Y" ]; then
            echo "Gonna term here"

            echo "Terminating Instances and spot requests"
            for INST in $INST_STR; do
                IID=$(echo "$INST"|cut -d"," -f1)
                SID=$(echo "$INST"|cut -d"," -f2)
                IIP=$(echo "$INST"|cut -d"," -f3)
                EIP=$(echo "$INST"|cut -d"," -f4)

                echo "Canceling Spot Request for $SID which is instance $IID running on $IIP/$EIP"
                aws ec2 cancel-spot-instance-requests --spot-instance-request-ids $SID
                aws ec2 terminate-instances --instance-ids $IID
            done
            echo ""
            echo "Removing ./bin/init_output.json"
            rm ./bin/init_output.json
        else
            echo "Not Terminitating"
        fi
    fi

}
_term_nodes "$@"



