#!/bin/bash

#
# Delete an Establshed LB  a loadbalancer based on the provied information
##
sourceconf "$PLATFORM_CONF"
sourceconf "$K8S_CONF"
function _deletelb(){
 for i in "$@"
        do
        case $i in
            -u)
            UNATTEND="1"
            ;;
            *)
            # unknown option
            ;;
        esac
    done


    if [ "$LBARN" == "" ]; then
        @go.log FATAL "No LBARN defined in k8s.conf - exiting"
    fi
    if [ "$TGARN" == "" ]; then
        @go.log FATAL "No TGARN defined in k8s.conf - exiting"
    fi

# To delete them
    if [ "$UNATTEND" != "1" ]; then
        read -e -p "Do you wish to deleted Target group $TGARN and Load Balancer $LBARN? (Y/N): " -i "N" DELME
        if [ "$DELME" != "Y" ]; then
            @go.log FATAL "User decided against delete!"
        fi
    fi
    echo ""
    @go.log INFO "Trying to delete LB $LBARN"
    echo ""
    delete_network_lb "$LBARN" "RES"
    if [ "$RES" == "0" ]; then
        @go.log INFO "Network Loadbalancer $LBARN Deleted!"
    else
        @go.log WARN "Network Loadbalancer $LBARN could not be deleted!!!!"
    fi

    echo ""
    @go.log INFO "Trying to delete TG $TGARN"
    echo ""
    delete_network_lb_tg "$TGARN" "RES"
    if [ "$RES" == "0" ]; then
        @go.log INFO "Network Loadbalancer Target Group $TGARN Deleted!"
    else
        @go.log WARN "Network Loadbalancer $TGARN could not be deleted!!!!"
    fi

echo ""
echo "Load Balancer Deleted: "
echo "-----------------------"
echo "LB DNS: $LBDBS"
echo "LB Arn: $LBARN"
echo "Target Group Arn: $TGARN"
echo "Listener Arn: $LISTENERARN"
echo ""
echo "This information will be removed from K8S Conf at $K8S_CONF"
echo ""
echo "-----------------------"

sed -i "s/LBARN=.*//g" $K8S_CONF
sed -i "s/TGARN=.*//g" $K8S_CONF
sed -i "s/LISTENERARN=.*//g" $K8S_CONF
sed -i "s/LBDNS=.*//g" $K8S_CONF

}
_deletelb "$@"



