#!/bin/bash




sed "s@etcd_ca: \"\"@etcd_ca: \"/calico-secrets/etcd-ca\"@g" ./calico.yaml > calico_out.yaml

sed -i "s@etcd_cert: \"\"@etcd_cert: \"/calico-secrets/etcd-cert\"@g" ./calico_out.yaml
sed -i "s@etcd_key: \"\"@etcd_key: \"/calico-secrets/etcd-key\"@g" ./calico_out.yaml


sed -i "s@# etcd-key: null@etcd-key: mynewkey@g" ./calico_out.yaml


