#!/bin/bash
#
# helm - Scripts to interact with the shared filesystem in Zeta
#
#
#
sourceconf "$PLATFORM_CONF"
sourceconf "$CA_CONF"
sourceconf "$K8S_CONF"
sourceconf "$PREP_CONF"

function _helm() {

    LOCK="0"
    UNATTEND="0"
    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$HELM_CONF" "$@"

    echo ""
    echo "********************************"
    echo ""
    echo "Commands to use with helm:"
    echo ""
    echo "./zeta helm installhelm   # Install the helm"
    echo "./zeta helm installtiller # Install the tiller"
    echo ""
    echo "./zeta helm -l            # lock or unlock  helm.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$HELM_CONF"
    fi

}

_helm "$@"

