#!/bin/bash
#
# k8s - Scripts to stage and usek8s on a Zeta Cluster
#
#

sourceconf "$CA_CONF"
sourceconf "$PLATFORM_CONF"

function _k8s() {

    LOCK="0"
    UNATTEND="0"
    for i in "$@"
    do
    case $i in
        -l)
        LOCK="1"
        ;;
        -u)
        UNATTEND="1"
        ;;
        *)
            # unknown option
        ;;
    esac
    done

    initconf "$K8S_CONF" "$UNATTEND"

    echo ""
    echo "********************************"
    echo "It is highly advised to run the k8s  Scripts on the cluster initial node specified in the prep stage"
    echo "That should be: $INIT_NODE"
    echo "********************************"
    echo ""
    echo "Commands to use with k8s:"
    echo ""
    echo "./zeta k8s createlb          # Create a LB for the K8s cluster"
    echo "./zeta k8s install -n=NODE1  # Install k8s on NODE1 given k8s.conf"
    echo "./zeta k8s install -a        # Install k8s on all nodes listed in k8s.conf"
    echo ""
    echo "./zeta k8s sshhosts          # One time script to connect to each nodes internal IP, hostname, and FQ hostname to trust the ssh host key - Not needed but helps automate"
    echo ""
    echo "./zeta k8s -l                # Lock or unlock k8s.conf file"
    echo ""


    if [ "$LOCK" == "1" ]; then
       lockconf "$k8s_CONF"
    fi

}

_k8s "$@"

