#!/bin/bash
#
# This script walks the user through a series of questions in order to create a prep_conf.conf
#
# No arguments are called here
sourceconf "$PLATFORM_CONF"
sourceconf "$CA_CONF"
sourceconf "$K8S_CONF"
sourceconf "$PREP_CONF"

DEF_HELM_VERS="2.12.1"

function _helmcreateconf() {

    UNATTEND="0"
    for i in "$@"
    do
    case $i in
        -u)
        UNATTEND="1"
        ;;
        "-hv="*)
        T_HELM_VERS="${i#*=}"
        ;;
        *)
    esac
    done

    if [ "$UNATTEND" == "1" ]; then
        HELM_VERS=${T_HELM_VERS:-$DEF_HELM_VERS}
    else
        echo ""
        read -e -p "What version of Helm/Tiller should we install:  " -i "$DEF_HELM_VERS" HELM_VERS
        echo ""
    fi

    HELM_FILE="helm-v\${HELM_VERS}-linux-amd64.tar.gz"
    HELM_URL="https://storage.googleapis.com/kubernetes-helm/\${HELM_FILE}"

    touch $HELM_CONF
    chmod 640 $HELM_CONF


cat > $HELM_CONF << EOF
#
# Configuration script for prepping nodes for Zeta Architecture

HELM_VERS="$HELM_VERS"
HELM_FILE="$HELM_FILE"
HELM_URL="$HELM_URL"


# If this is set to 1, scripts will assume "Use" when the conf exists.
HELM_LOCKED="1"

EOF

    @go.log INFO "Helm Conf file written to $HELM_CONF"
}
_helmcreateconf "$@"
